### ISSUE TITLE
AppVeyor buid fails

### ISSUE THREAD

**Issue by wasd171** [YellowKirby/is-ci-cli#2]
Hi!

My build on AppVeyor fails with:
```
> chatinder@1.4.5 postinstall C:\projects\chatinder
> is-ci 'ci:skip' 'install:types'
internal/child_process.js:317
    throw errnoException(err, 'spawn');
    ^
Error: spawn UNKNOWN
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:317:11)
    at Object.exports.spawn (child_process.js:471:9)
    at run (C:\projects\chatinder\node_modules\is-ci-cli\cli.js:11:23)
    at Object.<anonymous> (C:\projects\chatinder\node_modules\is-ci-cli\cli.js:25:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

**Comment by wasd171** [comment]
Might be [related](https://github.com/nodejs/node/issues/3675)
