### ISSUE TITLE
Spawn is not a function

### ISSUE THREAD

**Issue by edouardr** [YellowKirby/is-ci-cli#9]
I just upgraded to version 2.1.0. Since then, my npm scripts are failing with the following error:

```
return spawn(
                       ^

TypeError: spawn is not a function
    at run (/Users/***/node_modules/is-ci-cli/cli.js:29:10)
    at Object.<anonymous> (/Users/***/node_modules/is-ci-cli/cli.js:42:16)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

My script is as follow:
```
  "scripts": {
    "build": "is-ci \"build:production\" \"build:tsc\"",
    "build:tsc": "tsc",
    "build:production": "npm run prestart",
  }
```

And my dependencies like:

```
  "devDependencies": {
    "is-ci-cli": "^2.1.0",
  },
```

Not sure if I am missing a dependency or not.

**Comment by edouardr** [comment]
@YellowKirby thanks! Got `2.1.1` and it works as expected!
